export type * from '@idraw/types';
export {
  Sharer,
  Calculator,
  Core,
  Board,
  MiddlewareSelector,
  MiddlewareCreator,
  MiddlewareDragger,
  MiddlewareInfo,
  MiddlewareLayoutSelector,
  MiddlewarePointer,
  MiddlewareScroller,
  MiddlewareScaler,
  MiddlewareRuler,
  MiddlewareTextEditor,
  MiddlewarePathCreator,
  MiddlewarePathEditor,
  coreEventKeys,
} from '@idraw/core';
export { Renderer } from '@idraw/renderer';
export {
  delay,
  compose,
  throttle,
  debounce,
  downloadImageFromCanvas,
  parseFileToBase64,
  pickFile,
  parseFileToText,
  downloadFileFromText,
  toColorHexStr,
  toColorHexNum,
  isColorStr,
  colorNameToHex,
  colorToCSS,
  colorToLinearGradientCSS,
  mergeHexColorAlpha,
  createUUID,
  createId,
  isAssetId,
  createAssetId,
  deepClone,
  deepCloneData,
  sortDataAsserts,
  istype,
  loadImage,
  loadSVGCode,
  loadForeignObject,
  is,
  check,
  createBoardContent,
  createContext2D,
  createOffscreenContext2D,
  EventEmitter,
  calcDistance,
  // calcSpeed,
  // equalPoint,
  // equalTouchPoint,
  // vaildPoint,
  // vaildTouchPoint,
  getCenterFromTwoPoints,
  Store,
  getViewScaleInfoFromSnapshot,
  getViewSizeInfoFromSnapshot,
  Context2D,
  rotateMaterial,
  parseRadianToAngle,
  parseAngleToRadian,
  rotateMaterialVertexes,
  getMaterialRotateVertexes,
  calcMaterialCenter,
  calcMaterialCenterFromVertexes,
  rotatePointInGroup,
  limitAngle,
  getSelectedMaterialUUIDs,
  validateMaterials,
  calcMaterialsContextSize,
  calcMaterialsViewInfo,
  calcMaterialListSize,
  getMaterialsAssetIds,
  findMaterialFromList,
  findMaterialsFromList,
  findMaterialFromListByPosition,
  findMaterialsFromListByPositions,
  findMaterialQueueFromListByPosition,
  getMaterialPositionFromList,
  getMaterialPositionMapFromList,
  updateMaterialInList,
  getGroupQueueFromList,
  getMaterialSize,
  mergeMaterialAsset,
  filterMaterialAsset,
  isResourceMaterial,
  checkRectIntersect,
  viewScale,
  viewScroll,
  calcViewMaterialSize,
  calcViewPoint,
  calcViewVertexes,
  isViewPointInMaterial,
  getViewPointAtMaterial,
  isMaterialInView,
  rotatePoint,
  rotateVertexes,
  getMaterialVertexes,
  calcMaterialVertexesInGroup,
  calcMaterialVertexesQueueInGroup,
  calcMaterialQueueVertexesQueueInGroup,
  calcMaterialSizeController,
  convertPathCommandsToStr,
  parseSVGPath,
  generateHTML,
  parseHTML,
  compressImage,
  formatNumber,
  matrixToAngle,
  matrixToRadian,
  getDefaultMaterialAttributes,
  createMaterial,
  moveMaterialPosition,
  insertMaterialToListByPosition,
  deleteMaterialInListByPosition,
  deleteMaterialInList,
  deepCloneMaterial,
  calcViewCenterContent,
  calcViewCenter,
  calcMaterialViewBoundingInfo,
  calcMaterialBoundingInfo,
  flatMaterialList,
  calcPointMoveMaterialInGroup,
  merge,
  omit,
  toFlattenMaterial,
  toFlattenGlobal,
  toFlattenLayout,
  flatObject,
  unflatObject,
  set,
  get,
  mergeMaterial,
  calcResultMovePosition,
  calcRevertMovePosition,
  svgToMaterial,
  materialToSVG,
  dataToSVG,
} from '@idraw/util';
export { iDraw } from './idraw';
export { eventKeys } from './event';
export type { IDrawEvent, IDrawEventKeys } from './event';
export type { ExportImageFileResult, ExportImageFileBaseOptions } from './file';
export { useHistory } from './middlewares/use-history';
